#!/bin/sh -e

machine=$(cc -dumpmachine)

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --build="$machine" \
    --host="$machine" \
    --disable-blkid

for p in *.patch; do
    patch -p1 < "$p"
done

make
make DESTDIR="$1" install
